### ISSUE TITLE
wrong return on begin

### ISSUE THREAD

**Issue by DavidNidam** [RobTillaart/PCF8575#40] opened 2024-04-09 15:59 UTC
Hey

Call begin for the first time when no using interrupt and writeMode & readMode == 0 return fail because transmissionStatus == 4.

Reproduce:
1. run ESP8266
2. define PCF8575 pcf8575(0x20);
3. call:     if (pcf8575.begin())
        Serial.println(F("OK"));
    else
        Serial.println(F("Failed"));
4. wrong behavior... always return fail

**Comment by RobTillaart** [comment] 2024-04-09 16:04
Thanks for the issue, 
Will look into it later this week (busy)

**Comment by RobTillaart** [comment] 2024-04-09 16:10
transmissionStatus == 4

Thanks for this analysis, need to check the details of the I2C implementation of the ESP8266.

**Comment by RobTillaart** [comment] 2024-04-09 18:21
Library code context

```cpp
bool PCF8575::begin(uint16_t value)
{
  if (! isConnected()) return false;   <<<<<<<<<<<
  PCF8575::write16(value);
  return true;
}


bool PCF8575::isConnected()
{
  _wire->beginTransmission(_address);
  return ( _wire->endTransmission() == 0);   <<<<<<<<<<
}
```

**Comment by RobTillaart** [comment] 2024-04-09 18:25
> Reproduce:
> 
> 1. run ESP8266
> 2. define PCF8575 pcf8575(0x20);
> 3. call:     if (pcf8575.begin())
>    Serial.println(F("OK"));
>    else
>    Serial.println(F("Failed"));
> 4. wrong behavior... always return fail

I cannot reproduce from that (as it is no code), but I will do a call stack trace

**Comment by RobTillaart** [comment] 2024-04-09 18:31
@DavidNidam 
### Wire.cpp

```cpp
uint8_t TwoWire::endTransmission(uint8_t sendStop)
{
    int8_t ret     = twi_writeTo(txAddress, txBuffer, txBufferLength, sendStop);   <<<<<<<<<<
    txBufferIndex  = 0;
    txBufferLength = 0;
    transmitting   = 0;
    return ret;
}
```

### core_esp8266_si2c.cpp
```cpp
    uint8_t twi_writeTo(unsigned char address, unsigned char* buf, unsigned int len,
                        unsigned char sendStop)
    {
        return twi.writeTo(address, buf, len, sendStop);   <<<<<<<<<<<<<<<
    }
```


### core_esp8266_si2c.cpp  (again)

```cpp
unsigned char Twi::writeTo(unsigned char address, unsigned char* buf, unsigned int len,
                           unsigned char sendStop)
{
    unsigned int i;
    if (!write_start())
    {
        return 4;  // line busy   <<<<<<<<<<<<<<<<<<<<<<<<<<<<  Here is your 4 
    }
    if (!write_byte(((address << 1) | 0) & 0xFF))
    {
        if (sendStop)
        {
            write_stop();
        }
        return 2;  // received NACK on transmit of address
    }
    for (i = 0; i < len; i++)
    {
        if (!write_byte(buf[i]))
        {
            if (sendStop)
            {
                write_stop();
            }
            return 3;  // received NACK on transmit of data
        }
    }
    if (sendStop)
    {
        write_stop();
    }
    else
    {
        twi_scl_valley();
        // TD-er: Also busywait(twi_dcount) here?
        // busywait(twi_dcount);
    }
    i = 0;
    while (!SDA_READ(twi_sda) && (i++) < 10)
    {
        twi_scl_valley();
        busywait(twi_dcount);
    }
    return 0;    <<<<<<<<<<<<  this is the zero when all goes well 
}
```

### core_esp8266_si2c.cpp  (again)

```cpp
bool Twi::write_start(void)
{
    SCL_HIGH(twi_scl);
    SDA_HIGH(twi_sda);
    if (!SDA_READ(twi_sda))
    {
        return false;    <<<<<<<<<<<<<<<<
    }
    busywait(twi_dcount);
    // A high-to-low transition on the SDA line while the SCL is high defines a START condition.
    SDA_LOW(twi_sda);
    busywait(twi_dcount);
    // An additional delay between the SCL line high-to-low transition and setting up the SDA line
    // to prevent a STOP condition execute.
    SCL_LOW(twi_scl);
    busywait(twi_dcount);
    return true;
}
```

So your I2C seems not to be in a ready or start state.

what seems to go wrong is the **SDA_HIGH(twi_sda);** call.

Did you call **Wire.begin()** in your sketch ?

**Comment by DavidNidam** [comment] 2024-04-10 06:37
Hey

 

No need to reproduce… just look at the code…

 

Line 167 -> this->transmissionStatus = 4;

Line 192-> if (writeMode>0 || readMode>0) -> false

Line 211-> if (_usingInterrupt) ->  false

 

Results: transmissionStatus at 4 (never changed)

 

Thus line 220-> return this->isLastTransmissionSuccess(); -> return transmissionStatus==0;

IE begin return false even though everything is OK

 

David

**Comment by RobTillaart** [comment] 2024-04-10 07:08
You refer to line numbers of which file?
Please provide URL

**Comment by RobTillaart** [comment] 2024-04-10 08:18
@DavidNidam 

Your error comes from the PCF8575 library from xreef. 

> No need to reproduce… just look at the code…

https://github.com/xreef/PCF8575_library/blob/master/PCF8575.cpp#L167

**Comment by DavidNidam** [comment] 2024-04-10 13:45
Yep

That’s what I referred to…

**Comment by RobTillaart** [comment] 2024-04-10 13:56
> Yep That’s what I referred to…

That's not my library, so you need to open an issue at his repository.

**Comment by RobTillaart** [comment] 2024-04-16 19:33
@DavidNidam 
As this is not an issue of my library I close the issue.

**Closed as completed by RobTillaart** 2024-04-16 19:33 UTC
Labels: question

**Comment by DavidNidam** [comment] 2024-04-17 05:53
Sure.
Sorry for the mistake


Dady
Sent from my Samsung Galaxy smartphone.
________________________________
